"""
Built-in CompanyProfile presets for non-LLM mode.
Each preset provides realistic departments, job titles, and office locations
for a given industry vertical.
"""

from company import CompanyProfile

PRESETS: dict[str, CompanyProfile] = {

    "healthcare": CompanyProfile(
        name="Regional Health System",
        industry="Healthcare",
        description="A regional health system providing acute care, outpatient services, and community health programs.",
        departments=[
            "Clinical Operations",
            "Nursing",
            "Pharmacy",
            "Radiology & Imaging",
            "Laboratory Services",
            "Patient Services",
            "Health Informatics",
            "Compliance & Risk",
            "Human Resources",
            "Finance",
        ],
        job_titles=[
            "Registered Nurse",
            "Licensed Practical Nurse",
            "Nurse Practitioner",
            "Physician Assistant",
            "Medical Technologist",
            "Radiologic Technologist",
            "Pharmacist",
            "Pharmacy Technician",
            "Clinical Informatics Analyst",
            "Health Information Manager",
            "Patient Care Coordinator",
            "Medical Coder",
            "Compliance Officer",
            "Clinical Data Analyst",
            "Healthcare Administrator",
            "Revenue Cycle Specialist",
            "Social Worker",
            "Physical Therapist",
            "Occupational Therapist",
            "Quality Improvement Specialist",
        ],
        office_locations=[
            {"city": "Chicago", "country": "United States", "domain": "regionalhealthsystem.org"},
            {"city": "Houston", "country": "United States", "domain": "regionalhealthsystem.org"},
            {"city": "Phoenix", "country": "United States", "domain": "regionalhealthsystem.org"},
            {"city": "Philadelphia", "country": "United States", "domain": "regionalhealthsystem.org"},
        ],
    ),

    "university": CompanyProfile(
        name="State University",
        industry="Higher Education",
        description="A public research university offering undergraduate, graduate, and professional degree programs.",
        departments=[
            "Academic Affairs",
            "Student Services",
            "Research & Innovation",
            "Information Technology",
            "Facilities Management",
            "Finance & Administration",
            "Human Resources",
            "Library Services",
            "Enrollment Management",
            "Athletics",
        ],
        job_titles=[
            "Professor",
            "Associate Professor",
            "Assistant Professor",
            "Lecturer",
            "Research Scientist",
            "Postdoctoral Researcher",
            "Academic Advisor",
            "Registrar Specialist",
            "Financial Aid Counselor",
            "IT Systems Administrator",
            "Network Engineer",
            "Library Specialist",
            "Grants Administrator",
            "Student Affairs Coordinator",
            "Admissions Counselor",
            "Facilities Technician",
            "Budget Analyst",
            "Communications Specialist",
            "Lab Manager",
            "Curriculum Developer",
        ],
        office_locations=[
            {"city": "Columbus", "country": "United States", "domain": "stateuniversity.edu"},
            {"city": "Austin", "country": "United States", "domain": "stateuniversity.edu"},
            {"city": "Madison", "country": "United States", "domain": "stateuniversity.edu"},
            {"city": "Raleigh", "country": "United States", "domain": "stateuniversity.edu"},
        ],
    ),

    "government": CompanyProfile(
        name="Federal Agency",
        industry="Government",
        description="A federal government agency responsible for policy development, regulatory oversight, and public services.",
        departments=[
            "Policy & Legislation",
            "Legal Affairs",
            "Public Affairs",
            "Information Technology",
            "Human Capital",
            "Finance & Budget",
            "Procurement",
            "Audit & Inspection",
            "Operations",
            "Cybersecurity",
        ],
        job_titles=[
            "Policy Analyst",
            "Program Manager",
            "Budget Analyst",
            "Contract Specialist",
            "Procurement Officer",
            "IT Specialist",
            "Cybersecurity Analyst",
            "Legal Counsel",
            "Public Affairs Specialist",
            "Administrative Officer",
            "Management Analyst",
            "Human Capital Specialist",
            "Auditor",
            "Inspector General Investigator",
            "Data Scientist",
            "Records Manager",
            "Grants Management Specialist",
            "Compliance Analyst",
            "Legislative Affairs Specialist",
            "Operations Research Analyst",
        ],
        office_locations=[
            {"city": "Washington", "country": "United States", "domain": "agency.gov"},
            {"city": "Arlington", "country": "United States", "domain": "agency.gov"},
            {"city": "Atlanta", "country": "United States", "domain": "agency.gov"},
            {"city": "Denver", "country": "United States", "domain": "agency.gov"},
            {"city": "Kansas City", "country": "United States", "domain": "agency.gov"},
        ],
    ),

    "finance": CompanyProfile(
        name="National Financial Group",
        industry="Finance & Insurance",
        description="A diversified financial services firm offering banking, investment management, and insurance products.",
        departments=[
            "Retail Banking",
            "Commercial Banking",
            "Investment Management",
            "Risk Management",
            "Compliance & Regulatory Affairs",
            "Insurance Underwriting",
            "Claims",
            "Actuarial",
            "Finance & Accounting",
            "Information Technology",
            "Human Resources",
        ],
        job_titles=[
            "Financial Analyst",
            "Investment Analyst",
            "Portfolio Manager",
            "Risk Analyst",
            "Compliance Officer",
            "Underwriter",
            "Claims Adjuster",
            "Actuary",
            "Actuarial Analyst",
            "Loan Officer",
            "Credit Analyst",
            "Relationship Manager",
            "Treasury Analyst",
            "Financial Advisor",
            "Quantitative Analyst",
            "Anti-Money Laundering Analyst",
            "Internal Auditor",
            "Tax Analyst",
            "Business Analyst",
            "Data Analyst",
        ],
        office_locations=[
            {"city": "New York", "country": "United States", "domain": "nationalfinancialgroup.com"},
            {"city": "Charlotte", "country": "United States", "domain": "nationalfinancialgroup.com"},
            {"city": "Chicago", "country": "United States", "domain": "nationalfinancialgroup.com"},
            {"city": "London", "country": "United Kingdom", "domain": "nationalfinancialgroup.com"},
            {"city": "Toronto", "country": "Canada", "domain": "nationalfinancialgroup.com"},
        ],
    ),

    "manufacturing": CompanyProfile(
        name="Industrial Manufacturing Corp",
        industry="Manufacturing",
        description="A global manufacturer of industrial components and consumer goods with operations across multiple continents.",
        departments=[
            "Production",
            "Engineering",
            "Quality Assurance",
            "Supply Chain",
            "Procurement",
            "Logistics",
            "Health, Safety & Environment",
            "Research & Development",
            "Finance",
            "Human Resources",
            "Sales & Marketing",
        ],
        job_titles=[
            "Production Supervisor",
            "Manufacturing Engineer",
            "Process Engineer",
            "Quality Control Inspector",
            "Quality Assurance Engineer",
            "Supply Chain Analyst",
            "Procurement Specialist",
            "Logistics Coordinator",
            "Maintenance Technician",
            "Industrial Engineer",
            "CNC Machinist",
            "Welding Technician",
            "EHS Specialist",
            "Materials Planner",
            "Lean Manufacturing Specialist",
            "Product Development Engineer",
            "Plant Manager",
            "Warehouse Supervisor",
            "Cost Accountant",
            "Sales Engineer",
        ],
        office_locations=[
            {"city": "Detroit", "country": "United States", "domain": "industrialmfgcorp.com"},
            {"city": "Cleveland", "country": "United States", "domain": "industrialmfgcorp.com"},
            {"city": "Stuttgart", "country": "Germany", "domain": "industrialmfgcorp.com"},
            {"city": "Monterrey", "country": "Mexico", "domain": "industrialmfgcorp.com"},
            {"city": "Shanghai", "country": "China", "domain": "industrialmfgcorp.com"},
        ],
    ),

    "pharma": CompanyProfile(
        name="BioMed Sciences",
        industry="Pharma & Medical Device",
        description="A life sciences company focused on pharmaceutical development, clinical research, and medical device innovation.",
        departments=[
            "Research & Development",
            "Clinical Affairs",
            "Regulatory Affairs",
            "Quality Assurance",
            "Manufacturing",
            "Medical Affairs",
            "Pharmacovigilance",
            "Commercial Operations",
            "Supply Chain",
            "Finance",
            "Legal & Compliance",
            "Human Resources",
        ],
        job_titles=[
            "Research Scientist",
            "Senior Research Scientist",
            "Clinical Research Associate",
            "Clinical Trial Manager",
            "Regulatory Affairs Specialist",
            "Regulatory Affairs Manager",
            "Quality Assurance Specialist",
            "Validation Engineer",
            "Pharmacovigilance Specialist",
            "Medical Science Liaison",
            "Biostatistician",
            "Data Manager",
            "Drug Safety Analyst",
            "Process Development Scientist",
            "Formulation Scientist",
            "Medical Device Engineer",
            "Quality Systems Manager",
            "Supply Chain Analyst",
            "Market Access Analyst",
            "Compliance Specialist",
        ],
        office_locations=[
            {"city": "Boston", "country": "United States", "domain": "biomedsciences.com"},
            {"city": "San Diego", "country": "United States", "domain": "biomedsciences.com"},
            {"city": "Basel", "country": "Switzerland", "domain": "biomedsciences.com"},
            {"city": "Dublin", "country": "Ireland", "domain": "biomedsciences.com"},
            {"city": "Singapore", "country": "Singapore", "domain": "biomedsciences.com"},
        ],
    ),

    "utility": CompanyProfile(
        name="National Energy Utility",
        industry="Utility",
        description="A regulated utility company providing electricity, natural gas, and water services to residential and commercial customers.",
        departments=[
            "Generation",
            "Transmission & Distribution",
            "Grid Operations",
            "Engineering",
            "Environmental & Regulatory",
            "Customer Operations",
            "Information Technology",
            "Asset Management",
            "Finance",
            "Human Resources",
            "Safety",
        ],
        job_titles=[
            "Electrical Engineer",
            "Power Systems Engineer",
            "Grid Operations Analyst",
            "Transmission Line Technician",
            "Substation Technician",
            "SCADA Engineer",
            "Environmental Compliance Specialist",
            "Regulatory Affairs Analyst",
            "Customer Service Representative",
            "Metering Technician",
            "Asset Management Analyst",
            "GIS Analyst",
            "Project Manager",
            "Civil Engineer",
            "Control Room Operator",
            "Safety Specialist",
            "Energy Analyst",
            "Rate Analyst",
            "IT Systems Administrator",
            "Field Service Technician",
        ],
        office_locations=[
            {"city": "Atlanta", "country": "United States", "domain": "nationalenergyutility.com"},
            {"city": "Columbus", "country": "United States", "domain": "nationalenergyutility.com"},
            {"city": "Minneapolis", "country": "United States", "domain": "nationalenergyutility.com"},
            {"city": "Portland", "country": "United States", "domain": "nationalenergyutility.com"},
        ],
    ),
}

INDUSTRY_CHOICES = list(PRESETS.keys())


def get_preset(industry: str) -> CompanyProfile:
    """Return the CompanyProfile preset for the given industry key."""
    key = industry.lower()
    if key not in PRESETS:
        raise ValueError(
            f"Unknown industry '{industry}'. "
            f"Available options: {', '.join(INDUSTRY_CHOICES)}"
        )
    return PRESETS[key]
